### ISSUE TITLE
Showing more than one field in a row in edit dialog.

### ISSUE THREAD

**Issue by dfaruque** [volkanceylan/Serenity#157]
Is there any example or guidance to show more than one field in a row in edit dialog?

**Comment by volkanceylan** [comment]
Need to do it with CSS floats, here is some sample, masked from our forms:

```css
    div.field.XDerece, div.field.XKademe, div.field.XABCGun, div.field.XABCAy {
        width: 80px;
        float: left;

        label.caption {
            width: 35px;
        }

        input.editor {
            width: 29px;
            text-align: center;
        }
    }

    div.field.XDerece {
        clear: left;
    }
```
