### ISSUE TITLE
Master/Detail Editing

### ISSUE THREAD

**Issue by vinaykulkarni89** [volkanceylan/Serenity#1729]
![image](https://cloud.githubusercontent.com/assets/17939331/21631230/ef99c542-d25e-11e6-859f-756c0c24b085.png)

in above is it possible to increase the height of the marked box

**Comment by dfaruque** [comment]
try to play with css. :)

**Comment by vinaykulkarni89** [comment]
yes tried with master and detail also

**Comment by Estrusco** [comment]
```css
s-XYZDialog {
    > .size { .widthAndMin(800px); .heightAndMin(700px); }
    .caption { width: 150px; }

    @media(min-width:768px)
    {
        .s-XYZ-YourMasterDetailtsEditor > .grid-container{
            height: 300px;
        }
    }
}
```
