### ISSUE TITLE
Conditional Formatting In Grid Rows

### ISSUE THREAD

**Issue by satsokn** [volkanceylan/Serenity#1924]
i am trying to do the same as in example Conditional Formatting In Grid Rows. 
but unfortunately it doesn't work this is my code:
```

namespace ServiceOverview {
    
    @Serenity.Decorators.registerClass()
    @Serenity.Decorators.filterable()
    export class ServiceOverviewGrid extends Serenity.EntityGrid<ServiceOverviewRow, any> {
        protected getColumnsKey() { return 'ServiceOverview'; }
        protected getDialogType() { return <any>ServiceOverviewDialog; }  //<any>
        protected getIdProperty() { return ServiceOverviewRow.idProperty; }
        protected getLocalTextPrefix() { return ServiceOverviewRow.localTextPrefix; }
        protected getService() { return ServiceOverviewService.baseUrl; }

        constructor(container: JQuery) {
            super(container);
        }
        
        protected getColumns(): Slick.Column[] {
            let columns = super.getColumns();
            let fld = ServiceOverviewRow.Fields;
            
            
            columns = columns.filter(x => x.field !== fld.Description);
            Q.first(columns, x => x.field == fld.Code).cssClass += " col-unit-price";
           

            return columns;

        }

        protected getItemCssClass(item: ServiceOverview.ServiceOverviewRow, index: number): string {   //index row
            let klass: string = "";

            if (+item.Code >= 50)
                klass += " high-price";
            else if (+item.Code >= 20)
                klass += " medium-price";
            else if (+item.Code >= 0)
                klass += " low-price";
            
            return Q.trimToNull(klass);
        }
    }
}
```
and this is the code inside site.less

```
.s-ServiceOverviewGrid .high-price .col-unit-price {
        background-color: darkorchid;
        color: #fff;
    }

 .s-ServiceOverviewGrid   .medium-price .col-unit-price {
        background-color: yellow;
        color: #000;
    }

 .s-ServiceOverviewGrid   .low-price .col-unit-price {
        background-color: green;
        color: #fff;
    }
```

**Comment by Estrusco** [comment]
Try with .s-ServiceOverview-ServiceOverviewGrid in place of  .s-ServiceOverviewGrid

**Comment by satsokn** [comment]
have already done that but didnt work

```
.s-ServiceOverviewDialog {
    > .size { width: 650px; }
    .caption { width: 150px; }
}
```
the code for dialog is working.
any other thoughts?

**Comment by satsokn** [comment]
the css is not assigned to grid. how can i findout where the issue is?

**Comment by Estrusco** [comment]
![cattura](https://cloud.githubusercontent.com/assets/16304015/22829005/8c6eb86a-efa0-11e6-96f3-fe6b884437d7.PNG)

**Comment by Estrusco** [comment]
```less
.s-BasicSamples-ConditionalFormattingGrid {

    .discontinued .slick-cell, .discontinued .slick-cell a {

        color: lightgray;

    }



    .out-of-stock .slick-cell, .out-of-stock .slick-cell a {

        background-color: #ffaaaa;

        color: red;

    }



    .critical-stock {

        background-color: #ffd5c0;



        .slick-cell, .slick-cell a {

            color: black;

        }

    }



    .much-stock {



        .slick-cell, .slick-cell a {

            font-style: italic;

        }

    }



    .high-price .col-unit-price {

        background-color: darkorchid;

        color: #fff;

    }



    .medium-price .col-unit-price {

        background-color: yellow;

        color: #000;

    }



    .low-price .col-unit-price {

        background-color: green;

        color: #fff;

    }

}
```
