### ISSUE TITLE
RTL layout .Net Core css issue fix

### ISSUE THREAD

**Issue by mafdy** [volkanceylan/Serenity#3654]
Hello dears, as for .net core version RTL layout needs a little modifications. here it is.
modification will be in site.rtl.css inside wwwroot\content\site, Just find those styles and replace with current  values
@volkanceylan by the way, if you noticed, demo version style having some issues when choose culture with  RTL layout.
```css
.main-sidebar, .left-side {
    right: 0 !important;
    left: auto !important;
    width:230px;
}

.control-sidebar-bg, .control-sidebar {
    left: -250px;
    right: auto;
}

.ui-dialog .ui-dialog-titlebar-close {
    left: -120px;
    right: auto;
    margin: -15px 0 0 0;
}
```
Mafdy
Best Regards,
