### ISSUE TITLE
Increase width of quickfilter

### ISSUE THREAD

**Issue by ms4hafiz** [volkanceylan/Serenity#4367]
I want to increase the width of quickfilter dynamically to content length better  or fixed length. 

![image](https://user-images.githubusercontent.com/20435849/55308307-963a0a80-546f-11e9-8b31-583ab07faf09.png)

Any solution please.

I tried using CSS but did not succeed.

Thank you

**Comment by promiseap2014** [comment]
1. Add cssClass to the filter
```js
protected getQuickFilters() {
    var flt = super.getQuickFilters();
    var supplier = Q.tryFirst(flt, f => f.field == ProductRow.Fields.SupplierID);
    supplier.cssClass = 'supplier-filter';

    return flt;
}
```
2. Add style in less file
```css
.s-Northwind-ProductGrid {
    .supplier-filter {
        .select2-container {
            width:300px !important;
        }
    }
}
```
