### ISSUE TITLE
Add tooltip to NavigationItem

### ISSUE THREAD

**Issue by mfathy00** [volkanceylan/Serenity#4497]
Hi i would like to add tooltip to NavigationItem but i can't because navigation item in shared layout

**Comment by JohnRanger** [comment]
Good point. Although there is a Title attribute, setting it out does not show up a tooltip.

Question is then: Does Serenity have a working tooltip framework? 

A quick look through the scriptbundle.json file of V3.9.6 does not show any tooltip framework. But even then it should show the standard tooltip (which it does not).

John

**Comment by JohnRanger** [comment]
Hi @mfathy00 ,

if you use a recent Serenity Framework, you can assign a specific css class to a specific NavigationItem and then later assign the title attribute to the element with the above generated css class - like this:

Your navigation item:
```cs
[assembly: NavigationLink(2100, "TACMasterLayouts/Layouts & addit. Docs/Add, Edit, Del Layouts", typeof(RALayoutManager3.TACMasterLayouts.Pages.TacMasterLayoutsController), icon: "fa-plus", ItemClass ="MyTooltip1")]
```

(see the ItemClass = "MyTooltip1")

Then - for example in your _layout.cshtml file - in the **$().ready section** at the very bottom of this function, add the following line:

```js
$('.MyTooltip1').prop('title', 'your new tooltip text');
```

This looks then like this (with standard builtin tooltips) if you hoover over the relevant navigation item:

![Tooltip on NavItems](https://user-images.githubusercontent.com/2699447/60631316-3735ba00-9dff-11e9-9d27-1071867bff1c.png)

Hope, this helps.

With kind regards,

John

**Comment by JohnRanger** [comment]
or - as a bonus - with popper.js and tippy.js:

![Tooltip2](https://user-images.githubusercontent.com/2699447/60632807-f2625100-9e07-11e9-9f27-dd02d7aaddfc.png)

(1) Install popper.js and tippy.js (and their additional files), using npm.
(2) add the following css to serenity.css:

```css
.tippy-tooltip {
    font-size: 1.3rem;
    padding: 8px;
    background-color: #aa069d;
    border-radius: 2px;
    border: 1px thin black;
    color: white;
}

.tippy-popper[x-placement^=top] .tippy-arrow {
    border-top: 7px solid #aa069d;
}
```

Add the following line to _layout.cshtml instead of the above $():
```js
tippy('.MyTooltip1', { content: '<b>your new tooltip text</b>', arrow: true, arrowType: 'sharp', animation: 'fade', theme: 'light'});
```

That's it.

With kind regards,

John
