### ISSUE TITLE
[Tutorial] How to change serenity form's style from horizontal to vertical

### ISSUE THREAD

**Issue by minhhungit** [volkanceylan/Serenity#4634]
Serenity generates form very flexible, we can custom category, tab, column layout and much more…
But currently it just support horizontal form like this:

![image](https://user-images.githubusercontent.com/2279508/65842166-dc572480-e353-11e9-8ea2-249772bdb7d7.png)

Luckily I know a way to change it to vertical style, demo image:

![image](https://user-images.githubusercontent.com/2279508/65842172-e11bd880-e353-11e9-9ae8-ce71d9c52a2f.png)

You just need to put bellow code into your \Content\site\site.less then build solution

```css
.s-Supplier-SupplierDialog {
    > .size {
        .widthAndMin(480px);
        .heightAndMin(635px);
    }

    .caption {
        width: 150px;
        margin-bottom: 2px;
        text-align: left;
        flex-basis: 100%;
    }

    .field {
        flex-wrap: wrap;
    }
}
```

> Here .s-Supplier-SupplierDialog is class name of your dialog.

Okay, but that is just applied for only one dialog (SupplierDialog), right? Yes, correct!

If you want to apply it for all dialogs in your Serenity project, use bellow css:
```css
.s-Form label.caption {
    margin-bottom: 2px;
    text-align: left;
    flex-basis: 100%;
}

.flex-layout .field {
    flex-wrap: wrap;
}
```

**Note:**
I strongly recommend that you should change style for some specific dialogs, for dialog that has many fields in your form, vertical style will look a mess.
