### ISSUE TITLE
draggable grouping expand/collapse should be float right

### ISSUE THREAD

**Issue by minhhungit** [volkanceylan/Serenity#4682]
Hello, this might a bug

![image](https://user-images.githubusercontent.com/2279508/67376175-e3b5ca80-f5ad-11e9-8a19-52744f4bd5e8.png)

**Comment by kilroyFR** [comment]
Are you sure it's not a brower issue ?

i dont have this on mine (chrome)
![image](https://user-images.githubusercontent.com/31513956/67402899-8459b980-f5b1-11e9-8ad8-ec5409c34f3e.png)

**Comment by kilroyFR** [comment]
Well, works on IE 11 too

![image](https://user-images.githubusercontent.com/31513956/67403205-e5818d00-f5b1-11e9-8397-b8d52e080b3b.png)

**Comment by minhhungit** [comment]
this code is quick fix solution, put it on grouping page, it might help someone

```css
<style type="text/css">
    .slick-grouping-panel{
        position: unset !important;
    }
</style>
```
