### ISSUE TITLE
Change font of Field Text on dialog

### ISSUE THREAD

**Issue by waqarkabir** [volkanceylan/Serenity#5196]

**Comment by minhhungit** [comment]
put this on your site.less
```less
.s-Default-TimelogRecordDialog {
    .caption {
        font-size: 20px;
        font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;
    }
}
```

result

![image](https://user-images.githubusercontent.com/2279508/92413146-eba43c00-f178-11ea-851d-d2f930a86c4f.png)
