### ISSUE TITLE
Changing Global Font

### ISSUE THREAD

**Issue by paulobriennz** [volkanceylan/Serenity#883]
Thanks yet again for your awesome template you have built and all the work you continue to put in to it.

Quick question, is there a simple way to chnage the font used by the grids and forms?  I am relatiuvely new to MVC templates so just wondered if you knew of an easy way before researching how to do this in all the packages..

**Comment by jsbUSMC** [comment]
Check the less files. There's variables for the fonts used that you can alter.

**Comment by jsbUSMC** [comment]
Site.theme.less check the body element has font-family you can change there

**Comment by volkanceylan** [comment]
site.theme.less has font definition below:

```css
body {
    font-family: 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif;
    font-size: 13px;
    color: #000;
    -ms-overflow-style: scrollbar;
}
```

Changing it should be enough. If you are gonna use non-standard font, you should also include it in LayoutHead.cshtml, just like we include Open Sans from google.
