### ISSUE TITLE
Change edit form layout.

### ISSUE THREAD

**Issue by reybatacjr** [volkanceylan/Serenity#918]
How can I change the current edit form layout? say I want phone number and mobile number side by side on one row. or first, middle, last name on one row.
Thanks

**Comment by jsbUSMC** [comment]
Check multi column dialog in Serene Basic Samples

**Comment by reybatacjr** [comment]
I have seen that and thought its just an empty shell because constructor only have super(). Thanks anyway I will look at it further.

**Comment by Estrusco** [comment]
You can achieve this with css. 
In content site find your css class

```css
s-XYZDialog {
    > .size { width: 800px; height: 650px; }
    .caption { width: 150px; }

    @media (min-width: 768px) {
        .field.Phone, .field.Mobile
        {
            flex: auto;
            min-width: 50%;
        }
    }
}
```
