### ISSUE TITLE
Switch to Node.js nuget package instead of tools\node.exe

### ISSUE THREAD

**Issue by wldkrd1** [volkanceylan/Serenity#974]
One less binary to include in the solution. tools\Node\lessc.cmd would change to look like:

`@IF EXIST "%~dp0\..\..\.bin\node.cmd" (
  @IF EXIST "%~dp0\less\lib\lessc" (
    "%~dp0\..\..\.bin\node.cmd"  "%~dp0\less\lib\lessc" %*
  ) ELSE (
    "%~dp0\..\..\.bin\node.cmd" "%~dp0\less\bin\lessc" %*
  )
) ELSE (
  @IF EXIST "%~dp0\less\lib\lessc" (
    node  "%~dp0\less\lib\lessc" %*
  ) ELSE (
    node  "%~dp0\less\bin\lessc" %*
  )
)`

**Comment by volkanceylan** [comment]
Yes it is now possible as we are installing packages now from nuget not template. Is there a way to run this less without node at all? :)

**Comment by wldkrd1** [comment]
Anything's possible, but that's outside my area of expertise...

**Comment by wldkrd1** [comment]
You can also switch to NuGet's Mono.Cecil, that'll save you another 400KB. I've been running with that for the last couple months without an issue.

**Comment by volkanceylan** [comment]
Only problem with that is Nuget puts packages in versioned folders, so it's not easy to reference such assemblies from T4 template

**Comment by wldkrd1** [comment]
Ahh...hmm. You can't use $(TargetDir) ?

**Comment by volkanceylan** [comment]
Web app shouldn't have a reference to Cecil, it's a tool used at development time

**Comment by wldkrd1** [comment]
Not arguing, just confused...it's referenced in Modules\Common\Imports\CodeGenerationHelpers.ttinclude

You're saying that the intention is that they are included in the tools folder in the project but are not deployed to the webserver, which is why you don't want them referenced?

**Comment by volkanceylan** [comment]
Yes, because at runtime they are of no use. But as they are in bin folder, and your Site.Web.dll has a reference to them, they would be loaded anyway. Yes they are not big files and would probably not hurt much.

**Comment by volkanceylan** [comment]
Btw, node and cecil is in Serenity.Web.Tooling package, which i version differently than other nuget packages of Serenity. So at the moment, having them in another nuget.org package or my Serenity.Web.Tooling doesn't make much difference. They are not embedded in template.

**Comment by jsbUSMC** [comment]
We could switch entirely to Sass `.scss` instead of Less. I prefer to work with sass, I like the syntax better, and it does some cool things that less cannot. For example, when we extend a class in Less, it'll copy all of the properties from the base class to the extended class in CSS. In Sass, it rewrites selectors to remove code bloat. So the following stuff written in Less:

```less
.base {
    font-size: 14px;
    font-family: 'Arial', 'Helvetica', sans-serif;
    line-height: 1.4;
    color: #222222;
}

.extended-class {
    .base(); /* All of the props from .base will be copied in compiled css */
    border: 1px solid red;
}
```

Would have this CSS output:

```css
.base {
    font-size: 14px;
    font-family: 'Arial', 'Helvetica', sans-serif;
    line-height: 1.4;
    color: #222222;
}

.extended-class {
    font-size: 14px;
    font-family: 'Arial', 'Helvetica', sans-serif;
    line-height: 1.4;
    color: #222222;
    border: 1px solid red;
}
```

Whereas with Sass extend we would see the following:

```scss
.base {
    font-size: 14px;
    font-family: 'Arial', 'Helvetica', sans-serif;
    line-height: 1.4;
    color: #222222;
}

.extended-class {
    @extend .base;
    border: 1px solid red;
}
```

Compile to:

```css
.base, .extended-class {
    font-size: 14px;
    font-family: 'Arial', 'Helvetica', sans-serif;
    line-height: 1.4;
    color: #222222;
}

.extended-class {
    border: 1px solid red;
}
```

I also like the fact that the variable operator in Sass is `$` instead of `@`, seeing as how this is a reserved symbol in css, like defining `@media` or `@keyframes`. The only issue that may be present here is having to have Ruby downloaded and installed. However, if you were to include ruby as you have node, I believe the Ruby binary is smaller size than node.
